### ISSUE TITLE
Commands overriding in sim device and control device seem to be mutually exclusive, respectively

### ISSUE THREAD

**Issue by kmadisa** [ska-sa/tango-simlib#145]
## Problem Description

I had a look at the weather simulator we have in tango-simlib. It seems there is a bug related to overriding the commands in both the sim device and the control device, respectively.
What I noted is that it only overrides the commands for only one of the devices but not both.

Could be related to https://github.com/ska-sa/tango-simlib/blob/2d07fbdce4c6ec92d1c3f2d68453032f70e8506a/tango_simlib/tests/test_sim_test_interface.py#L402

Noted in this example simulator https://github.com/ska-sa/tango-simlib/blob/master/tango_simlib/examples/weather3.py.

**Comment by kmadisa** [comment]
Added a simple test that calls a command on the sim device in the class https://github.com/ska-sa/tango-simlib/blob/2d07fbdce4c6ec92d1c3f2d68453032f70e8506a/tango_simlib/tests/test_sim_test_interface.py#L311

```python
def test_Add(self):
        command_name = "Add"
        expected_value = 5
        actual_value = self.sim_device.command_inout(command_name, [3, 2])
        time.sleep(1)
        self.assertEqual(
            expected_value,
            actual_value)
```

That resulted in an error:
```bash
test_Add (tango_simlib.tests.test_sim_test_interface.test_TangoSimGenDeviceIntegration) ... omniORB: (6) 2021-11-29 09:51:19.888749: Warning: method 'command_inout_4' raised an unexpected exception (not a CORBA exception).
ERROR

======================================================================
ERROR: test_Add (tango_simlib.tests.test_sim_test_interface.test_TangoSimGenDeviceIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tango-simlib/tango_simlib/tests/test_sim_test_interface.py", line 401, in test_Add
    actual_value = self.sim_device.command_inout(command_name, [3, 2])
  File "/usr/local/lib/python3.7/dist-packages/tango/green.py", line 195, in greener
    return executor.run(fn, args, kwargs, wait=wait, timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/tango/green.py", line 109, in run
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tango/connection.py", line 108, in __Connection__command_inout
    r = Connection.command_inout_raw(self, name, *args, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/tango/connection.py", line 137, in __Connection__command_inout_raw
    return self.__command_inout(cmd_name, param)
PyTango.CommunicationFailed: DevFailed[
DevError[
    desc = UNKNOWN CORBA system exception
  origin = Connection::command_inout()
  reason = API_CorbaException
severity = ERR]

DevError[
    desc = Failed to execute command_inout on device test/nodb/tangodeviceserver, command Add
  origin = Connection::command_inout()
  reason = API_CommunicationFailed
severity = ERR]
]
```

**Comment by kmadisa** [comment]
```console
In [66]: model.sim_actions['Command1']
Out[66]: functools.partial(<function PopulateModelActions.generate_action_handler.<locals>.action_handler at 0x7f7ddeac98c8>, <tango_simlib.model.Model object at 0x7f7ddeecbb70>)

In [67]: model.test_sim_actions['Command1']
Out[67]: functools.partial(<bound method TestSimControl.test_action_command1 of <test_module.TestSimControl object at 0x7f7ddecf6588>>, <tango_simlib.model.Model object at 0x7f7ddeecbb70>)
```

**Comment by kmadisa** [comment]
```ipython
command_info.update(psr.get_device_command_metadata())
command_info
Out[52]: 
{'Command1': {'name': 'Command1',
  'description': 'Runs command2',
  'actions': [],
  'dtype_in': tango._tango.CmdArgType.DevVoid,
  'doc_in': 'No input parameter',
  'dformat_in': tango._tango.AttrDataFormat.SCALAR,
  'dtype_out': tango._tango.CmdArgType.DevVoid,
  'doc_out': 'Command responds',
  'dformat_out': tango._tango.AttrDataFormat.SCALAR},
 'test_Command1': {'name': 'test_Command1',
  'description': 'Runs command1',
  'dtype_in': tango._tango.CmdArgType.DevVoid,
  'doc_in': 'No input parameter',
  'dformat_in': tango._tango.AttrDataFormat.SCALAR,
  'dtype_out': tango._tango.CmdArgType.DevVoid,
  'doc_out': 'Command responds',
  'dformat_out': tango._tango.AttrDataFormat.SCALAR}}
```

**Comment by kmadisa** [comment]
```ipython3
override_info.update(psr.get_device_cmd_override_metadata())
In [53]: override_info
Out[53]: 
{'Sim_Test': {'name': 'Sim_Test',
  'module_directory': '/tango_simlib/scripts/',
  'module_name': 'test_module',
  'class_name': 'TestSim'},
 'SimControl_Test': {'name': 'SimControl_Test',
  'module_directory': '/tango_simlib/scripts/',
  'module_name': 'test_module',
  'class_name': 'TestSimControl'}}
```

**Comment by kmadisa** [comment]
Files used to reproduce the issue (NB: the files were placed in the `scripts/` directory):

- [test_module.py](https://gist.github.com/kmadisa/bf418c6ecade7cab28267e3820b1f83a)
- [test_SimDD.json](https://gist.github.com/kmadisa/a420cedc2cb4ef5c3c53f2b1a7406681)
- [TestDevice.py](https://gist.github.com/kmadisa/3b17d4c5204d4f49400803361f3b9ca0)
