### ISSUE TITLE
Unicode Encode Error from POGO xmi

### ISSUE THREAD

**Issue by Athanaseus** [ska-sa/tango-simlib#57]
```kat@levpro.devj2.camlab.kat.ac.za:/usr/local/bin$ SrvPDU-simlib Elt
Traceback (most recent call last):
 File "/usr/local/bin/SrvPDU-simlib", line 16, in <module>
   main()
 File "/usr/local/bin/SrvPDU-simlib", line 12, in main
   TangoDeviceServers = get_tango_device_server(model, sim_data_files)
 File "/usr/local/lib/python2.7/dist-packages/tango_simlib/tango_sim_generator.py", line 236, in get_tango_device_server
   quantity.meta)
 File "/usr/local/lib/python2.7/dist-packages/tango_simlib/tango_sim_generator.py", line 164, in add_static_attribute
   access=getattr(AttrWriteType, attr_meta['writable']))
 File "/usr/local/lib/python2.7/dist-packages/tango/server.py", line 806, in __init__
   self.build_from_dict(kwargs)
 File "/usr/local/lib/python2.7/dist-packages/tango/attr_data.py", line 132, in build_from_dict
   self.att_prop = self.__create_user_default_attr_prop(attr_dict)
 File "/usr/local/lib/python2.7/dist-packages/tango/attr_data.py", line 172, in __create_user_default_attr_prop
   method(str(v))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 79: ordinal not in range(128)```

**Comment by ajoubertza** [comment]
This has been fixed in PR #59.
